In [1]:
import numpy as np


In [13]:
gr=np.array((30., 45., 60., 90., 180))

In [14]:
np.sin( gr * np.pi / 180. )

array([5.00000000e-01, 7.07106781e-01, 8.66025404e-01, 1.00000000e+00,
       1.22464680e-16])

In [15]:
np.cos( gr * np.pi / 180. )

array([ 8.66025404e-01,  7.07106781e-01,  5.00000000e-01,  6.12323400e-17,
       -1.00000000e+00])

In [16]:
np.tan( gr * np.pi / 180. )

array([ 5.77350269e-01,  1.00000000e+00,  1.73205081e+00,  1.63312394e+16,
       -1.22464680e-16])